### ISSUE TITLE
bug with incompatible settings

### ISSUE THREAD

**Issue by EuanKirkhope** [p12tic/eagle-brd-merge#1]
I get the following error running with a 80x32mm board created with eagle 7.3.0 win32, script running in linux:

Warning : Incompatible settings 
<setting alwaysvectorfont="no"/>

<setting verticaltext="up"/>

Traceback (most recent call last):
  File "./merge.py", line 585, in <module>
    main()
  File "./merge.py", line 578, in main
    merge_xml_eagle(out_el, in_el.getroot(), infile)
  File "./merge.py", line 564, in merge_xml_eagle
    merge_xml_drawing(find_or_create_child(out_el, "drawing"), child, infile)
  File "./merge.py", line 536, in merge_xml_drawing
    merge_xml_board(find_or_create_child(out_el, "board"), child, infile)
  File "./merge.py", line 497, in merge_xml_board
    append_xml_plain(find_or_create_child(out_el, "plain"), child, infile)
  File "./merge.py", line 360, in append_xml_plain
    update_routing(new_child, infile)
  File "./merge.py", line 338, in update_routing
    print_file_error_and_exit(infile, child)
UnboundLocalError: local variable 'child' referenced before assignment

the brd file is attached renamed as .txt:

[brd-file.txt](https://github.com/p12tic/eagle-brd-merge/files/106552/brd-file.txt)

**Comment by p12tic** [comment]
Thanks for the bug report. The real issue was that `<rectangle>` nodes were not supported and the script also crashed when trying to report this. This was fixed in 3c50673f37155 and d8b7b383b3c7fec1. Please disregard the "incompatible settings" warning for the moment.
